'use strict';
const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs/promises');const path=require('node:path');const {createSshProfileStore}=require('./ssh-profiles.cjs');const {createDirectoryParser,integrationCommand}=require('./ssh-directory.cjs');const {createSshConnections}=require('./ssh-connections.cjs');
test('saved profiles persist concurrently, deduplicate and never write credentials',async()=>{
 const root=await fs.mkdtemp(path.join(__dirname,'../.checks/profiles-'));const store=createSshProfileStore(root);await Promise.all(['one','two'].map(host=>store.save({host,username:'tester',port:22,authMode:'password',password:'secret',passphrase:'key-secret',privateKey:'secret-key'})));let entries=await createSshProfileStore(root).list();assert.equal(entries.length,2);const text=await fs.readFile(path.join(root,'ssh-sessions.json'),'utf8');assert(!text.includes('secret'));await store.save({...entries[0],label:'Renamed'});entries=await store.list();assert.equal(entries.length,2);assert.equal(entries[0].label,'Renamed');await store.remove(entries[0].id);assert.equal((await store.list()).length,1);await assert.rejects(store.save({host:'bad',username:'x',authMode:'agent'}));
});
test('directory reports survive split UTF-8 output and reject untrusted markers and invalid paths',()=>{
 const token='a'.repeat(32),seen=[];const parse=createDirectoryParser(token,p=>seen.push(p));const report=p=>Buffer.from('\x1b]777;pane-cwd;'+token+';'+Buffer.from(p).toString('base64')+'\x07');const data=Buffer.concat([Buffer.from('prompt 한글 '),report('/tmp/한글 폴더'),report('/next')]);for(let i=0;i<data.length;i+=3)parse(data.subarray(i,i+3));assert.deepEqual(seen,['/tmp/한글 폴더','/next']);parse(report('relative'));parse(report('/bad\nname'));parse(Buffer.from('\x1b]777;pane-cwd;'+'b'.repeat(32)+';L3Rlc3Q=\x07'));assert.equal(seen.length,2);assert.match(integrationCommand(token),/PROMPT_COMMAND/);assert.match(integrationCommand(token),/precmd_functions/);
});
test('multi connections isolate output, command targets, file destinations and cleanup',async()=>{
 const root=await fs.mkdtemp(path.join(__dirname,'../.checks/multi-'));const calls=[],events=[];let number=0;
 const registry=createSshConnections({directory:root,confirmHost:async()=>true,emit:(type,value)=>events.push({type,...value}),serviceFactory:options=>{const n=number++;return {connect:async input=>({host:input.host,username:input.username,port:22,path:'/home/test'}),disconnect:async()=>calls.push({n,close:true}),openTerminal:async()=>options.onTerminal({data:'eA=='}),writeTerminal:async data=>calls.push({n,data}),resizeTerminal:()=>{},acknowledgeTerminal:()=>{},transfer:async input=>{calls.push({n,transfer:input});return {completed:input.sources,failed:[]};}};}});
 const primary=await registry.connectPrimary({host:'one',username:'test',authMode:'default-key'});assert.equal(primary.sessions.length,1);const id=primary.sessions[0].id;const a=await registry.openSaved({profileId:id}),b=await registry.openSaved({profileId:id});assert.notEqual(a.connectionId,b.connectionId);await registry.open(a.connectionId,{cols:80,rows:24});assert.equal(events[0].connectionId,a.connectionId);
 await registry.broadcast({ids:[a.connectionId],data:'pwd\r'});assert.equal(calls.filter(c=>c.data).length,1);assert.equal(calls.find(c=>c.data).n,1);
 await registry.upload({sources:['C:\\file.txt'],targets:[{id:a.connectionId,destination:'/one'},{id:b.connectionId,destination:'/two'}]});assert.deepEqual(calls.filter(c=>c.transfer).map(c=>c.transfer.destination),['/one','/two']);await assert.rejects(registry.broadcast({ids:['missing'],data:'x'}));await registry.close(a.connectionId);await assert.rejects(registry.broadcast({ids:[a.connectionId],data:'x'}));await registry.disconnectAll();assert.equal(calls.filter(c=>c.close).length,3);
});
test('Bash prompt hook reports actual cd results without editing shell startup files',async t=>{
 const {spawn}=require('node:child_process');const bash=process.platform==='win32'?'C:/Program Files/Git/bin/bash.exe':'/bin/bash';try{await fs.access(bash);}catch{t.skip('Bash is unavailable');return;}
 const token='c'.repeat(32),directories=[];const parse=createDirectoryParser(token,p=>directories.push(p));const child=spawn(bash,['--noprofile','--norc','-i'],{windowsHide:true,env:{...process.env,HISTFILE:'/dev/null',PS1:'test> '},stdio:['pipe','pipe','pipe']});child.stdout.on('data',parse);child.stderr.resume();child.stdin.end(integrationCommand(token).replace(/\r$/,'\n')+'cd /tmp\nexit\n');const exit=await new Promise((resolve,reject)=>{child.once('error',reject);child.once('exit',resolve);});assert.equal(exit,0);assert(directories.includes('/tmp'),JSON.stringify(directories));
});
